#!/bin/bash

export COMPOSE_PROJECT_NAME=ignite

docker-compose stop
docker-compose kill

docker rmi -f $(docker images -a -q)
docker rm -f $(docker ps -a -q)

docker-compose build

docker-compose create
docker-compose start

docker ps
